In [28]:
import matplotlib.pyplot as plt
from generate_passive_simulations import *
from toddler.action_coding import get_mouse_action, mass_answers, force_answers

In [29]:
from isaac.visualization import make_frame_curried
import moviepy.editor as mpy

In [30]:
from isaac.dataset import read_dataset

In [42]:
def make_clip(trial_data):

    duration = len(trial_data)
    print(duration, "frames")

    n_bodies = sum(["o"+str(i)+".x" in list(trial_data.columns) for i in range(1, 5)])
    
    # while (len(trial_data) + 1) % 60 != 0:
    #    trial_data = trial_data.append(trial_data.iloc[-1], ignore_index=True)
    make_frame = make_frame_curried(trial_data, n_bodies)
    clip = mpy.VideoClip(make_frame, duration=duration / 60)
    return clip, trial_data

def get_replay(replays, include_control_replay, include_not_control_replay, step_size=None):
    lengths = [len(trial) for trial in replays]
    control = np.array([(trial.idControlledObject.isin(["object1", "object2"])).sum() for trial in replays])
    
    print(lengths)
    print(control)
    
    if not include_control_replay and not include_not_control_replay:
        return None
    
    if include_control_replay and not include_not_control_replay:
        if sum(control) == 0:
            return None
        random_trial = np.random.choice(np.where(control > 0)[0])
        
    elif not include_control_replay and include_not_control_replay:
        if sum(control) == len(control):
            return None
        random_trial = np.random.choice(np.where(control == 0)[0])
    
    else:
        random_trial = np.random.choice(len(control))
        
    trial_data = replays[random_trial].iloc[::step_size]

    return make_clip(trial_data)

In [43]:
replays = read_dataset("replays.h5")

100%|██████████| 10/10 [00:00<00:00, 171.25it/s]


In [44]:
display = None
data = get_replay(replays, include_control_replay=True, include_not_control_replay=False)

if data is not None:
    clip, trial_data = data
    display = clip.ipython_display(fps=60)
    
display

  8%|▊         | 18/225 [00:00<00:01, 173.66it/s]

[424, 82, 44, 132, 224, 28, 122, 276, 624, 114]
[1 1 1 1 1 1 1 1 1 1]
224 frames


100%|█████████▉| 224/225 [00:01<00:00, 184.35it/s]


In [45]:
display = None
data = get_replay(replays, include_control_replay=False, include_not_control_replay=True)

if data is not None:
    clip, trial_data = data
    display = clip.ipython_display(fps=60)
    
display

[424, 82, 44, 132, 224, 28, 122, 276, 624, 114]
[1 1 1 1 1 1 1 1 1 1]


In [46]:
print(np.unique(trial_data.actions, return_counts=True))
trial_data.iloc[-500:]

(array([0, 1, 2, 3, 4, 5]), array([11, 82,  8, 72, 40, 11]))


o1.x      o1.y     o1.vx     o1.vy  ground_truth  actions    mouseX  \
0    5.229095  2.114936  5.598174  4.459982  A is heavier        0  3.458972   
1    5.322320  2.189208  5.593509  4.456265  A is heavier        5  3.458972   
2    5.415467  2.263417  5.588848  4.452552  A is heavier        0  3.458972   
3    5.508537  2.337564  5.584190  4.448842  A is heavier        5  3.458972   
4    5.499591  2.407047 -5.467947  3.892760  A is heavier        0  3.458972   
5    5.408535  2.471872 -5.463390  3.889516  A is heavier        1  3.463138   
6    5.317554  2.536643 -5.458837  3.886275  A is heavier        1  3.471472   
7    5.226649  2.601361 -5.454288  3.883036  A is heavier        1  3.483972   
8    5.135820  2.666024 -5.449743  3.879800  A is heavier        1  3.500638   
9    5.045067  2.730633 -5.445201  3.876567  A is heavier        1  3.521472   
10   4.954389  2.795189 -5.440664  3.873337  A is heavier        1  3.546472   
11   4.863787  2.859691 -5.436130  3.870109  A is heavier        1  3.575638   
12   4.773260  2.924139 -5.431600  3.866884  A is heavier        1  3.608972   
13   4.682809  2.988533 -5.427074  3.863661  A is heavier        1  3.646472   
14   4.592433  3.052874 -5.422552  3.860442  A is heavier        1  3.688138   
15   4.502132  3.117161 -5.418033  3.857225  A is heavier        1  3.733972   
16   4.411907  3.181395 -5.413517  3.854010  A is heavier        1  3.783972   
17   4.321757  3.245575 -5.409006  3.850799  A is heavier        1  3.838138   
18   4.231682  3.309701 -5.404499  3.847589  A is heavier        1  3.896472   
19   4.141682  3.373774 -5.399995  3.844383  A is heavier        1  3.958972   
20   4.051757  3.437794 -5.395495  3.841180  A is heavier        1  4.025638   
21   3.961907  3.501760 -5.390999  3.837979  A is heavier        1  4.096472   
22   3.873189  3.535165 -5.006863 -3.758085  A is heavier        1  4.171472   
23   3.789811  3.472583 -5.002691 -3.754953  A is heavier        5  4.208972   
24   3.706502  3.410052 -4.998522 -3.751824  A is heavier        0  4.227722   
25   3.623263  3.347574 -4.994356 -3.748698  A is heavier        5  4.237097   
26   3.540093  3.285147 -4.990194 -3.745574  A is heavier        0  4.241784   
27   3.456992  3.222773 -4.986036 -3.742452  A is heavier        5  4.244128   
28   3.373961  3.160451 -4.981881 -3.739333  A is heavier        0  4.245300   
29   3.290999  3.098181 -4.977729 -3.736217  A is heavier        5  4.245886   
..        ...       ...       ...       ...           ...      ...       ...   
194  1.809184  1.254313 -3.656682 -2.329352  A is heavier        1  0.887500   
195  1.748290  1.215523 -3.653635 -2.327410  A is heavier        1  0.750000   
196  1.687447  1.176765 -3.650590 -2.325471  A is heavier        1  0.616667   
197  1.626655  1.138040 -3.647548 -2.323533  A is heavier        1  0.487500   
198  1.565913  1.099346 -3.644508 -2.321597  A is heavier        1  0.362500   
199  1.505222  1.060685 -3.641471 -2.319662  A is heavier        1  0.250000   
200  1.444581  1.022057 -3.638437 -2.317729  A is heavier        1  0.254167   
201  1.383991  0.983460 -3.635405 -2.315798  A is heavier        1  0.262500   
202  1.323451  0.944896 -3.632375 -2.313868  A is heavier        1  0.275000   
203  1.262962  0.906363 -3.629348 -2.311939  A is heavier        1  0.291667   
204  1.202523  0.867863 -3.626324 -2.310013  A is heavier        1  0.312500   
205  1.142135  0.829395 -3.623302 -2.308088  A is heavier        1  0.337500   
206  1.081797  0.790959 -3.620282 -2.306165  A is heavier        1  0.366667   
207  1.021509  0.752555 -3.617265 -2.304243  A is heavier        4  0.395833   
208  0.961272  0.714183 -3.614251 -2.302322  A is heavier        4  0.425000   
209  0.901085  0.675843 -3.611239 -2.300404  A is heavier        4  0.454167   
210  0.840947  0.637534 -3.608230 -2.298487  A is heavier        4  0.483333   
211  0.780860  0.599258 -3.605223 -2.296571  A is heavier        4  0.512500   
212  0.72

In [ ]:
trial_data.mouseY.iloc[-500:]

# All replays

In [49]:
all_replays = [make_clip(replay)[0] for replay in replays]

424 frames
82 frames
44 frames
132 frames
224 frames
28 frames
122 frames
276 frames
624 frames
114 frames


In [52]:
all_replays[0].ipython_display(fps=60)

100%|█████████▉| 424/425 [00:02<00:00, 180.05it/s]


In [53]:
all_replays[1].ipython_display(fps=60)

 99%|█████████▉| 82/83 [00:00<00:00, 175.69it/s]


In [54]:
all_replays[2].ipython_display(fps=60)

 98%|█████████▊| 44/45 [00:00<00:00, 173.65it/s]


In [55]:
all_replays[3].ipython_display(fps=60)

 99%|█████████▉| 132/133 [00:00<00:00, 179.58it/s]


In [56]:
all_replays[4].ipython_display(fps=60)

100%|█████████▉| 224/225 [00:01<00:00, 171.58it/s]


In [57]:
all_replays[5].ipython_display(fps=60)

 97%|█████████▋| 28/29 [00:00<00:00, 175.26it/s]


In [58]:
all_replays[6].ipython_display(fps=60)

 99%|█████████▉| 122/123 [00:00<00:00, 168.97it/s]


In [59]:
all_replays[7].ipython_display(fps=60)

100%|█████████▉| 276/277 [00:01<00:00, 179.86it/s]


In [60]:
all_replays[8].ipython_display(fps=60)

100%|█████████▉| 624/625 [00:03<00:00, 171.42it/s]


In [61]:
all_replays[9].ipython_display(fps=60)

 99%|█████████▉| 114/115 [00:00<00:00, 164.85it/s]
